import type { Metadata, Viewport } from 'next';
import { Inter, Inter_Tight, Instrument_Serif } from 'next/font/google';

import { Analytics } from '@/components/Analytics';
import { SmoothScroll } from '@/components/motion/SmoothScroll';
import { brandProfiles, ogImage, siteConfig } from '@/lib/site';
import { colors } from '@/lib/tokens';

import './globals.css';

/* ---------------------------------------------------------------------------
   Fonts.
   next/font self-hosts and preloads these at build time — no render-blocking
   request to Google, no layout shift (`display: swap` + size-adjust fallbacks).
--------------------------------------------------------------------------- */

/** Body / UI copy. */
const inter = Inter({
  subsets: ['latin'],
  variable: '--font-inter',
  display: 'swap',
});

/** Display headlines — tighter than Inter, gives the editorial punch. */
const interTight = Inter_Tight({
  subsets: ['latin'],
  weight: ['500', '600', '700'],
  variable: '--font-inter-tight',
  display: 'swap',
});

/** The handwritten-feeling italic accent — the slogan, "how it works", etc. */
const instrumentSerif = Instrument_Serif({
  subsets: ['latin'],
  weight: '400',
  style: 'italic',
  variable: '--font-instrument-serif',
  display: 'swap',
});

/* ---------------------------------------------------------------------------
   Metadata
--------------------------------------------------------------------------- */

export const metadata: Metadata = {
  metadataBase: new URL(siteConfig.url),
  title: {
    default: siteConfig.title,
    template: `%s - ${siteConfig.name}`,
  },
  description: siteConfig.description,
  applicationName: siteConfig.name,
  keywords: [
    'meal planning app',
    'supermarket price comparison',
    'grocery price comparison UK',
    'weekly meal planner',
    'cheap healthy recipes',
    'student food budget',
    'nutrition tracking',
    'food waste',
  ],
  authors: [{ name: siteConfig.name, url: siteConfig.url }],
  creator: siteConfig.name,
  publisher: siteConfig.name,
  /*
   * No `alternates.canonical` here, deliberately — it is set per page instead,
   * including on the home page.
   *
   * A canonical declared on the *layout* applies to every route that doesn't
   * override it, and it pointed at `/`. Every real page does override it, so
   * the visible symptom was only on the 404: `out/404.html` announced itself as
   * a copy of the home page while also being `noindex`, which is a
   * contradiction — one tag says "don't index me", the other says "index this
   * other URL in my place".
   *
   * The bigger reason is what it does to pages that don't exist yet. Forget the
   * override on a new route and it doesn't merely lose its canonical, it
   * inherits a *wrong* one telling Google the page is a duplicate of the home
   * page — the fastest way to have a page you just published quietly refuse to
   * rank. With nothing declared here, forgetting is harmless: a page with no
   * canonical is self-canonical by default.
   */
  /*
   * Social images point at real `.png` files in `public/`, generated by
   * `scripts/generate-og-image.mjs` (wired to `prebuild`).
   *
   * Next's `opengraph-image.tsx` convention would be tidier, but under
   * `output: 'export'` it emits an *extensionless* file served from an
   * extensionless URL. Static hosts then guess the content type, and every
   * major scraper refuses an og:image that isn't served as `image/*`.
   */
  openGraph: {
    type: 'website',
    locale: siteConfig.locale,
    url: siteConfig.url,
    siteName: siteConfig.name,
    title: siteConfig.title,
    description: siteConfig.description,
    images: [
      ogImage(
        `${siteConfig.name}: plan a week of meals and compare every ingredient across supermarkets.`,
      ),
    ],
  },
  twitter: {
    card: 'summary_large_image',
    site: siteConfig.twitter,
    creator: siteConfig.twitter,
    title: siteConfig.title,
    description: siteConfig.description,
    images: ['/og.png'],
  },
  /*
   * Every icon is listed explicitly. Declaring this object at all opts out of
   * Next's automatic detection of an `app/icon.*` file, so omitting an entry
   * here silently drops that link altogether.
   *
   * All of them are cropped from `Logo.png` by
   * `scripts/generate-logo-assets.mjs`. Two raster sizes rather than one: the
   * mark is detailed enough that browsers downscaling 512px to a 16px tab
   * render it as mush, so 32 is offered as the tab-sized original.
   *
   * No `.ico` entry: the scaffold shipped Next's own logo as favicon.ico, and
   * serving that as MealFind's mark would be worse than leaving pre-2013
   * browsers without one. Everything in support today reads PNG icons.
   *
   * Root-relative, like every other `public/` reference. Next resolves
   * `openGraph`/`twitter` URLs against `metadataBase` but emits `icons` and
   * `manifest` verbatim, which is correct here because the site is served from
   * the domain root — see the note in next.config.ts.
   */
  icons: {
    icon: [
      { url: '/icon-32.png', type: 'image/png', sizes: '32x32' },
      { url: '/icon-192.png', type: 'image/png', sizes: '192x192' },
      { url: '/icon-512.png', type: 'image/png', sizes: '512x512' },
    ],
    apple: [{ url: '/apple-touch-icon.png', sizes: '180x180' }],
  },
  manifest: '/site.webmanifest',
  /*
   * Deliberately no `index: true` / `follow: true`. That is already the default
   * for any page without a robots meta, so stating it bought nothing — and
   * because layout metadata applies to every route, it was also being emitted
   * on the 404, which Next separately (and correctly) marks `noindex`. The
   * exported 404.html carried both `<meta name="robots" content="noindex">` and
   * `<meta name="robots" content="index, follow">`. Crawlers resolve a conflict
   * like that by taking the most restrictive directive, so nothing was actually
   * being indexed that shouldn't be, but the page was giving two contradictory
   * instructions and relying on the tie-break to land the right way.
   *
   * `max-image-preview` is kept: it is not the default, and it lets Google show
   * a full-size thumbnail rather than a postage stamp next to the result.
   */
  robots: {
    googleBot: { 'max-image-preview': 'large' },
  },
  category: 'food',
  /*
   * Rendered only once a token is set — an empty `content` attribute is not a
   * no-op, it is a verification tag that fails, so the property never verifies
   * and the failure is invisible from here. See `GOOGLE_SITE_VERIFICATION`.
   */
  ...(siteConfig.googleSiteVerification
    ? { verification: { google: siteConfig.googleSiteVerification } }
    : {}),
};

export const viewport: Viewport = {
  themeColor: colors.cream,
  colorScheme: 'light',
};

/* ---------------------------------------------------------------------------
   Structured data — helps the app surface as a rich result.
--------------------------------------------------------------------------- */

const jsonLd = {
  '@context': 'https://schema.org',
  '@graph': [
    {
      '@type': 'MobileApplication',
      '@id': `${siteConfig.url}/#app`,
      name: siteConfig.name,
      /*
       * The *names* the app is known by, not a description of it — this field
       * used to hold `tagline`, which told a search engine that "The recipe app
       * that knows what things cost" is a second name for the product. It
       * isn't, and the one job `alternateName` does — letting a query written
       * a different way ("Meal Find") resolve to this entity — was going
       * unused. The tagline's real home is `description`, just below.
       */
      alternateName: [...siteConfig.alternateNames],
      description: siteConfig.description,
      url: siteConfig.url,
      applicationCategory: 'LifestyleApplication',
      applicationSubCategory: 'Food & Drink',
      operatingSystem: 'iOS, Android',
      inLanguage: 'en-GB',
      // Free beta. Update `price` if/when the app becomes paid.
      offers: {
        '@type': 'Offer',
        price: '0',
        priceCurrency: 'GBP',
        availability: 'https://schema.org/PreOrder',
      },
      featureList: [
        'Weekly meal planning',
        'Live supermarket price comparison',
        'Nutrition and macro tracking',
        'Budget-aware recipe discovery',
        'Consolidated shopping list',
      ],
      screenshot: `${siteConfig.url}/og.png`,
      publisher: { '@id': `${siteConfig.url}/#org` },
      // NOTE: intentionally no `aggregateRating` — Google requires ratings to
      // be genuine and visible on the page. Add it once you have real reviews.
    },
    {
      '@type': 'Organization',
      '@id': `${siteConfig.url}/#org`,
      name: siteConfig.name,
      alternateName: [...siteConfig.alternateNames],
      url: siteConfig.url,
      email: siteConfig.email,
      /*
       * The off-site pages that are unambiguously this brand. This is what
       * turns a name into an *entity* in a search index: the site, the store
       * listings and the social accounts get joined into one thing, and a
       * search for the name resolves to that thing rather than to whichever
       * page happens to contain the string.
       *
       * Empty until there is something real to point at — see `profiles` in
       * site.ts. The key is omitted entirely when so, because `sameAs: []` is
       * an explicit claim to have no other presence anywhere.
       */
      ...(brandProfiles().length > 0 ? { sameAs: brandProfiles() } : {}),
      // Full stacked lockup, not the bare mark — Google shows this one.
      logo: `${siteConfig.url}/logo.png`,
      slogan: siteConfig.slogan,
      description: 'A student-built team making healthy eating affordable.',
    },
    {
      '@type': 'WebSite',
      '@id': `${siteConfig.url}/#website`,
      url: siteConfig.url,
      name: siteConfig.name,
      alternateName: [...siteConfig.alternateNames],
      description: siteConfig.description,
      inLanguage: 'en-GB',
      publisher: { '@id': `${siteConfig.url}/#org` },
    },
  ],
};

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <html
      lang="en-GB"
      className={`${inter.variable} ${interTight.variable} ${instrumentSerif.variable}`}
    >
      <head>
        {/*
          Entrance animations render their `hidden` state into the SSR markup
          (opacity 0, offset by a few px) and rely on JS to animate them in.
          With scripts blocked that would leave the page blank, so force every
          revealed element to its resting state instead. Scoped to
          `[data-reveal]`, which only `<Reveal>` sets.
        */}
        <noscript>
          <style>{`[data-reveal]{opacity:1!important;transform:none!important}`}</style>
        </noscript>
      </head>
      <body className="bg-cream text-ink antialiased">
        {/* Keyboard users land here first. */}
        <a
          href="#main"
          className="sr-only focus:not-sr-only focus:absolute focus:top-3 focus:left-3 focus:z-100 focus:rounded-full focus:bg-forest focus:px-5 focus:py-3 focus:text-sm focus:font-semibold focus:text-cream"
        >
          Skip to main content
        </a>

        <SmoothScroll>{children}</SmoothScroll>

        <script
          type="application/ld+json"
          // Content is a build-time constant, not user input.
          dangerouslySetInnerHTML={{ __html: JSON.stringify(jsonLd) }}
        />

        <Analytics />
      </body>
    </html>
  );
}
